services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
      - ./static:/app/static
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static/img:/static/img:ro
      - ./static/icon:/static/icon:ro
      - ./static/favicon.ico:/static/favicon.ico:ro
      - ./images:/images:ro
    networks:
      - internal

networks:
  internal:
    driver: bridge
